### ISSUE TITLE
Problem with "__file__"

### ISSUE THREAD

**Issue by euri412** [jexom/sd-webui-depth-lib#2] opened 2023-03-04 03:48 UTC
I downloaded the extension where they ask me to go but I get this error "__file__" I don't know what it refers to since I don't know the code, my apologies.

 File "C:\Users\EstudioEpika\Documents\stablediffusion\stable-diffusion-webui\modules\script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\EstudioEpika\Documents\stablediffusion\stable-diffusion-webui\extensions\sd-webui-depth-lib\scripts\main.py", line 40, in on_ui_tabs
    dataset = gr.Examples(examples=os.path.abspath(os.path.join(os.path.dirname(__file__), "../maps")), inputs=[png_input_area],examples_per_page=24,label="Depth Maps")
NameError: name '__file__' is not defined

I would like to be able to install it because I have in mind adding more hands.

**Comment by jexom** [comment] 2023-03-04 18:58
Do you use a local installation or a colab and if locally how are you launching it

**Comment by euri412** [comment] 2023-03-04 21:26
Hi Jexom. I am launching it locally. This error that I put here appears in the CMD, it allows me to open SD normally but I don't even see the "Depth Library" tab.

**Comment by robertalanbevan** [comment] 2023-03-05 02:03
I'm having the same issue. I'm running locally on Windows 10. In the last few months I've had some very messy and difficult-to-correct setups of Python, Anaconda, my temp directory and my PATH variables, and those tend to be at the root of my SD problems, but it could definitely be something else.

**Comment by Aghneel** [comment] 2023-03-05 12:08
This is probably due to different version of python, what version do you have? Personally works fine on Python 3.10.9

**Comment by robertalanbevan** [comment] 2023-03-05 12:25
> This is probably due to different version of python, what version do you have? Personally works fine on Python 3.10.9

In my case, 3.10.6 - the same for both my PATH Python and the version that came with that new pre-packaged version of A1111 that I use (whose name I forget).

**Comment by demirklvc** [comment] 2023-03-05 14:39
so how to fix???

**Comment by jexom** [comment] 2023-03-05 21:57
Yeah, I'm also using 3.10.9 with no problems. Can't reproduce and not that versed in python, to get a fast fix. For now I could suggest updating to 3.10.9, maybe that would resolve the issue for now

**Comment by Code4SAFrankie** [comment] 2023-03-05 22:11
Also have this issue on Python 3.10.6

**Comment by robertalanbevan** [comment] 2023-03-05 22:13
How do you install an embeddable version of Pyhton 3.10.9? I can only find installers that overwrite the previous installation.

**Comment by jexom** [comment] 2023-03-06 05:12
Try updating and using it now, switched to usinf the method provided in webui to get the base directory of the extension

**Comment by Adzeiros** [comment] 2023-03-06 05:49
I am still getting this error, even updated to python 3.10.9 and no help.

**Comment by jexom** [comment] 2023-03-06 06:11
> I am still getting this error, even updated to python 3.10.9 and no help.

Did you pull the latest commit?

**Comment by gatsu66** [comment] 2023-03-06 06:18
> > I am still getting this error, even updated to python 3.10.9 and no help.
> 
> Did you pull the latest commit?

Hello, I had an issue of the the script trying to search for the maps folder in the wrong place, with the lastest committ, I made a comment on it. I was able to fit it by editing line 40

            dataset = gr.Examples(examples=os.path.join(scripts.basedir(), "extensions\sd-webui-depth-lib\maps"), inputs=[png_input_area],examples_per_page=24,label="Depth Maps")

I am new to github so I don't really know how to submit the code officially, so I will just leave this in the comment.

Thank you for creating such a cool extension!

**Comment by jexom** [comment] 2023-03-06 06:21
Kinda strange. Going by the comments in scripts module of the webui it should return the directory of the extension not the root of webui. 
As for the pr, you make a fork, commit your changes and open a pull request, I'll commit your change for now

**Comment by neo** [comment] 2023-03-06 18:42
`scripts.basedir()` seems broken from the webui side, I guess for now I need to name the folder exactly `sd-webui-depth-lib`

**Comment by jexom** [comment] 2023-03-06 18:51
I actually got `scripts.basedir()` working. It has to be outside of the callback function because the callback function is executed from the modules directory

**Comment by neo** [comment] 2023-03-06 19:10
good to know, thanks for sharing!

and more importantly, thank you for making this ❤️

**Comment by robertalanbevan** [comment] 2023-03-06 20:26
The new version has fixed it for me. To be sure I was totally reinstalling, I deleted the folder sd-webui-depth-lib and reinstalled it entirely. This addon will be extremely helpful for me, thanks for making this!

**Comment by jexom** [comment] 2023-03-06 20:55
Should be fixed now, will close after feedback if resolved

**Comment by neo** [comment] 2023-03-06 21:11
can confirm the fix, thanks a lot!

**Comment by euri412** [comment] 2023-03-06 21:25
Confirmo! Me funciona.

I plan to work several hands, where can I send them to you so that you can put them in this extension?

![image](https://user-images.githubusercontent.com/120108555/223234085-f690c76e-08d2-4c4f-b6dd-0ed648036190.png)

**Comment by jexom** [comment] 2023-03-06 21:30
You can use the discussion thread #12.

**Comment by jexom** [comment] 2023-03-06 21:30
Fixed in 1d31c07

**Closed by jexom** 2023-03-06 21:30 UTC
