### ISSUE TITLE
Depth Library tab doesn't show

### ISSUE THREAD

**Issue by venyton** [jexom/sd-webui-depth-lib#4] opened 2023-03-04 21:15 UTC
Automatic1111 and ControlNet Extension are up to date. 
The extension appears in the extensions list, but the tab just doesn't show.
Tried restarting everything, no success.

**Comment by venyton** [comment] 2023-03-05 23:04
Launching Web UI with arguments: --xformers
Error loading script: posex.py
Traceback (most recent call last):
  File "C:\Stable diffusion 111\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stable diffusion 111\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Stable diffusion 111\webui\extensions\posex\scripts\posex.py", line 14, in <module>
    posex.set_save_dir(os.path.join(os.path.dirname(__file__), '..', 'saved_poses'))
NameError: name '__file__' is not defined

**Comment by venyton** [comment] 2023-03-05 23:05
Error executing callback ui_tabs_callback for C:\Stable diffusion 111\webui\extensions\sd-webui-depth-lib\scripts\main.py
Traceback (most recent call last):
  File "C:\Stable diffusion 111\webui\modules\script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Stable diffusion 111\webui\extensions\sd-webui-depth-lib\scripts\main.py", line 40, in on_ui_tabs
    dataset = gr.Examples(examples=os.path.abspath(os.path.join(os.path.dirname(__file__), "../maps")), inputs=[png_input_area],examples_per_page=24,label="Depth Maps")
NameError: name '__file__' is not defined

**Comment by jexom** [comment] 2023-03-06 04:39
Duplicate of #2

**Closed by jexom** 2023-03-06 04:39 UTC
Labels: duplicate
