### ISSUE TITLE
failed to add new .png to /maps folder for more hand shapes

### ISSUE THREAD

**Issue by stonegoGit** [jexom/sd-webui-depth-lib#3] opened 2023-03-04 15:30 UTC
The error message is listed below:
Error executing callback ui_tabs_callback for /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-depth-lib/scripts/main.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-depth-lib/scripts/main.py", line 40, in on_ui_tabs
    dataset = gr.Examples(examples=os.path.abspath(os.path.join(os.path.dirname(__file__), "../maps")), inputs=[png_input_area],examples_per_page=24,label="Depth Maps")
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/helpers.py", line 53, in create_examples
    examples_obj = Examples(
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/helpers.py", line 200, in __init__
    self.processed_examples = [
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/helpers.py", line 201, in <listcomp>
    [
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/helpers.py", line 202, in <listcomp>
    component.postprocess(sample)
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/components.py", line 1532, in postprocess
    return processing_utils.encode_url_or_file_to_base64(y)
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/processing_utils.py", line 62, in encode_url_or_file_to_base64
    return encode_file_to_base64(str(path), encryption_key=encryption_key)
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/processing_utils.py", line 86, in encode_file_to_base64
    with open(f, "rb") as file:
IsADirectoryError: [Errno 21] Is a directory: '.ipynb_checkpoints'
This occours after I added one new handshape.png to the /maps folder, and the extension didn't appear on the WebUI tab as a result.

**Comment by jexom** [comment] 2023-03-04 18:56
Could you upload the image in questuin, because I can't reproduce it. It's literally how I add the images to it myself

**Comment by stonegoGit** [comment] 2023-03-04 22:53
This error appears on my colab deployment, I tried to put the same image into local deployment, and the extension works fine with it, so I guess the problem is caused by the ‘os.path.abspath(os.path.join(os.path.dirname(file)’ command, which might need to be modified for colab installment.

**Comment by jexom** [comment] 2023-03-06 05:25
Well going by the stacktrace doesn't seem like it. In any case you could try updating as I switched to the webui method of getting the base extension path.

**Comment by jexom** [comment] 2023-03-06 21:07
Should be fixed by 1d31c07

**Comment by jexom** [comment] 2023-03-08 07:25
Closing due to inactivity

**Closed by jexom** 2023-03-08 07:25 UTC
