### ISSUE TITLE
Error: NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by demirklvc** [jexom/sd-webui-depth-lib#7] opened 2023-03-05 17:48 UTC
NameError: name 'file' is not defined.

please help.

**Comment by jexom** [comment] 2023-03-05 21:54
That alone doesn't tell me anything. There's a reason there's a template.
Possible duplicate of #2

**Comment by jexom** [comment] 2023-03-06 05:13
Try updating and using it now, switched to usinf the method provided in webui to get the base directory of the extension

**Comment by jexom** [comment] 2023-03-06 20:56
Assuming duplicate of #2

**Closed by jexom** 2023-03-06 20:56 UTC
Labels: bug
